// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net/pocrd/test/core/util/Test_Obj.proto

package net.pocrd.test.core.util;

public final class TestObj {
  private TestObj() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Test_ObjOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .net.pocrd.test.core.util.Test_String so = 1;
    /**
     * <code>optional .net.pocrd.test.core.util.Test_String so = 1;</code>
     */
    boolean hasSo();
    /**
     * <code>optional .net.pocrd.test.core.util.Test_String so = 1;</code>
     */
    net.pocrd.test.core.util.TestString.Test_String getSo();
    /**
     * <code>optional .net.pocrd.test.core.util.Test_String so = 1;</code>
     */
    net.pocrd.test.core.util.TestString.Test_StringOrBuilder getSoOrBuilder();

    // optional int32 i = 3;
    /**
     * <code>optional int32 i = 3;</code>
     *
     * <pre>
     *    repeated Test_String sos = 2;
     * </pre>
     */
    boolean hasI();
    /**
     * <code>optional int32 i = 3;</code>
     *
     * <pre>
     *    repeated Test_String sos = 2;
     * </pre>
     */
    int getI();

    // optional string s = 13;
    /**
     * <code>optional string s = 13;</code>
     *
     * <pre>
     *    repeated int32 is = 4;
     *
     *    optional int64 l = 5;
     *    repeated int64 ls = 6;
     *
     *    optional bool b = 7;
     *    repeated bool bs = 8;
     *
     *    optional float f = 9;
     *    repeated float fs = 10;
     *
     *    optional double d = 11;
     *    repeated double ds = 12;
     * </pre>
     */
    boolean hasS();
    /**
     * <code>optional string s = 13;</code>
     *
     * <pre>
     *    repeated int32 is = 4;
     *
     *    optional int64 l = 5;
     *    repeated int64 ls = 6;
     *
     *    optional bool b = 7;
     *    repeated bool bs = 8;
     *
     *    optional float f = 9;
     *    repeated float fs = 10;
     *
     *    optional double d = 11;
     *    repeated double ds = 12;
     * </pre>
     */
    java.lang.String getS();
    /**
     * <code>optional string s = 13;</code>
     *
     * <pre>
     *    repeated int32 is = 4;
     *
     *    optional int64 l = 5;
     *    repeated int64 ls = 6;
     *
     *    optional bool b = 7;
     *    repeated bool bs = 8;
     *
     *    optional float f = 9;
     *    repeated float fs = 10;
     *
     *    optional double d = 11;
     *    repeated double ds = 12;
     * </pre>
     */
    com.google.protobuf.ByteString
        getSBytes();
  }
  /**
   * Protobuf type {@code net.pocrd.test.core.util.Test_Obj}
   */
  public static final class Test_Obj extends
      com.google.protobuf.GeneratedMessage
      implements Test_ObjOrBuilder {
    // Use Test_Obj.newBuilder() to construct.
    private Test_Obj(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Test_Obj(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Test_Obj defaultInstance;
    public static Test_Obj getDefaultInstance() {
      return defaultInstance;
    }

    public Test_Obj getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Test_Obj(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              net.pocrd.test.core.util.TestString.Test_String.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = so_.toBuilder();
              }
              so_ = input.readMessage(net.pocrd.test.core.util.TestString.Test_String.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(so_);
                so_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              i_ = input.readInt32();
              break;
            }
            case 106: {
              bitField0_ |= 0x00000004;
              s_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.pocrd.test.core.util.TestObj.internal_static_net_pocrd_test_core_util_Test_Obj_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.pocrd.test.core.util.TestObj.internal_static_net_pocrd_test_core_util_Test_Obj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.pocrd.test.core.util.TestObj.Test_Obj.class, net.pocrd.test.core.util.TestObj.Test_Obj.Builder.class);
    }

    public static com.google.protobuf.Parser<Test_Obj> PARSER =
        new com.google.protobuf.AbstractParser<Test_Obj>() {
      public Test_Obj parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Test_Obj(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Test_Obj> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .net.pocrd.test.core.util.Test_String so = 1;
    public static final int SO_FIELD_NUMBER = 1;
    private net.pocrd.test.core.util.TestString.Test_String so_;
    /**
     * <code>optional .net.pocrd.test.core.util.Test_String so = 1;</code>
     */
    public boolean hasSo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .net.pocrd.test.core.util.Test_String so = 1;</code>
     */
    public net.pocrd.test.core.util.TestString.Test_String getSo() {
      return so_;
    }
    /**
     * <code>optional .net.pocrd.test.core.util.Test_String so = 1;</code>
     */
    public net.pocrd.test.core.util.TestString.Test_StringOrBuilder getSoOrBuilder() {
      return so_;
    }

    // optional int32 i = 3;
    public static final int I_FIELD_NUMBER = 3;
    private int i_;
    /**
     * <code>optional int32 i = 3;</code>
     *
     * <pre>
     *    repeated Test_String sos = 2;
     * </pre>
     */
    public boolean hasI() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 i = 3;</code>
     *
     * <pre>
     *    repeated Test_String sos = 2;
     * </pre>
     */
    public int getI() {
      return i_;
    }

    // optional string s = 13;
    public static final int S_FIELD_NUMBER = 13;
    private java.lang.Object s_;
    /**
     * <code>optional string s = 13;</code>
     *
     * <pre>
     *    repeated int32 is = 4;
     *
     *    optional int64 l = 5;
     *    repeated int64 ls = 6;
     *
     *    optional bool b = 7;
     *    repeated bool bs = 8;
     *
     *    optional float f = 9;
     *    repeated float fs = 10;
     *
     *    optional double d = 11;
     *    repeated double ds = 12;
     * </pre>
     */
    public boolean hasS() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string s = 13;</code>
     *
     * <pre>
     *    repeated int32 is = 4;
     *
     *    optional int64 l = 5;
     *    repeated int64 ls = 6;
     *
     *    optional bool b = 7;
     *    repeated bool bs = 8;
     *
     *    optional float f = 9;
     *    repeated float fs = 10;
     *
     *    optional double d = 11;
     *    repeated double ds = 12;
     * </pre>
     */
    public java.lang.String getS() {
      java.lang.Object ref = s_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          s_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string s = 13;</code>
     *
     * <pre>
     *    repeated int32 is = 4;
     *
     *    optional int64 l = 5;
     *    repeated int64 ls = 6;
     *
     *    optional bool b = 7;
     *    repeated bool bs = 8;
     *
     *    optional float f = 9;
     *    repeated float fs = 10;
     *
     *    optional double d = 11;
     *    repeated double ds = 12;
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSBytes() {
      java.lang.Object ref = s_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      so_ = net.pocrd.test.core.util.TestString.Test_String.getDefaultInstance();
      i_ = 0;
      s_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, so_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, i_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(13, getSBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, so_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, i_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getSBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static net.pocrd.test.core.util.TestObj.Test_Obj parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.pocrd.test.core.util.TestObj.Test_Obj parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.pocrd.test.core.util.TestObj.Test_Obj parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.pocrd.test.core.util.TestObj.Test_Obj parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.pocrd.test.core.util.TestObj.Test_Obj parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.pocrd.test.core.util.TestObj.Test_Obj parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.pocrd.test.core.util.TestObj.Test_Obj parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.pocrd.test.core.util.TestObj.Test_Obj parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.pocrd.test.core.util.TestObj.Test_Obj parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.pocrd.test.core.util.TestObj.Test_Obj parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.pocrd.test.core.util.TestObj.Test_Obj prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.pocrd.test.core.util.Test_Obj}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.pocrd.test.core.util.TestObj.Test_ObjOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.pocrd.test.core.util.TestObj.internal_static_net_pocrd_test_core_util_Test_Obj_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.pocrd.test.core.util.TestObj.internal_static_net_pocrd_test_core_util_Test_Obj_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.pocrd.test.core.util.TestObj.Test_Obj.class, net.pocrd.test.core.util.TestObj.Test_Obj.Builder.class);
      }

      // Construct using net.pocrd.test.core.util.TestObj.Test_Obj.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (soBuilder_ == null) {
          so_ = net.pocrd.test.core.util.TestString.Test_String.getDefaultInstance();
        } else {
          soBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        i_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        s_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.pocrd.test.core.util.TestObj.internal_static_net_pocrd_test_core_util_Test_Obj_descriptor;
      }

      public net.pocrd.test.core.util.TestObj.Test_Obj getDefaultInstanceForType() {
        return net.pocrd.test.core.util.TestObj.Test_Obj.getDefaultInstance();
      }

      public net.pocrd.test.core.util.TestObj.Test_Obj build() {
        net.pocrd.test.core.util.TestObj.Test_Obj result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.pocrd.test.core.util.TestObj.Test_Obj buildPartial() {
        net.pocrd.test.core.util.TestObj.Test_Obj result = new net.pocrd.test.core.util.TestObj.Test_Obj(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (soBuilder_ == null) {
          result.so_ = so_;
        } else {
          result.so_ = soBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.i_ = i_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.s_ = s_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.pocrd.test.core.util.TestObj.Test_Obj) {
          return mergeFrom((net.pocrd.test.core.util.TestObj.Test_Obj)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.pocrd.test.core.util.TestObj.Test_Obj other) {
        if (other == net.pocrd.test.core.util.TestObj.Test_Obj.getDefaultInstance()) return this;
        if (other.hasSo()) {
          mergeSo(other.getSo());
        }
        if (other.hasI()) {
          setI(other.getI());
        }
        if (other.hasS()) {
          bitField0_ |= 0x00000004;
          s_ = other.s_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.pocrd.test.core.util.TestObj.Test_Obj parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.pocrd.test.core.util.TestObj.Test_Obj) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .net.pocrd.test.core.util.Test_String so = 1;
      private net.pocrd.test.core.util.TestString.Test_String so_ = net.pocrd.test.core.util.TestString.Test_String.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          net.pocrd.test.core.util.TestString.Test_String, net.pocrd.test.core.util.TestString.Test_String.Builder, net.pocrd.test.core.util.TestString.Test_StringOrBuilder> soBuilder_;
      /**
       * <code>optional .net.pocrd.test.core.util.Test_String so = 1;</code>
       */
      public boolean hasSo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .net.pocrd.test.core.util.Test_String so = 1;</code>
       */
      public net.pocrd.test.core.util.TestString.Test_String getSo() {
        if (soBuilder_ == null) {
          return so_;
        } else {
          return soBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .net.pocrd.test.core.util.Test_String so = 1;</code>
       */
      public Builder setSo(net.pocrd.test.core.util.TestString.Test_String value) {
        if (soBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          so_ = value;
          onChanged();
        } else {
          soBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .net.pocrd.test.core.util.Test_String so = 1;</code>
       */
      public Builder setSo(
          net.pocrd.test.core.util.TestString.Test_String.Builder builderForValue) {
        if (soBuilder_ == null) {
          so_ = builderForValue.build();
          onChanged();
        } else {
          soBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .net.pocrd.test.core.util.Test_String so = 1;</code>
       */
      public Builder mergeSo(net.pocrd.test.core.util.TestString.Test_String value) {
        if (soBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              so_ != net.pocrd.test.core.util.TestString.Test_String.getDefaultInstance()) {
            so_ =
              net.pocrd.test.core.util.TestString.Test_String.newBuilder(so_).mergeFrom(value).buildPartial();
          } else {
            so_ = value;
          }
          onChanged();
        } else {
          soBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .net.pocrd.test.core.util.Test_String so = 1;</code>
       */
      public Builder clearSo() {
        if (soBuilder_ == null) {
          so_ = net.pocrd.test.core.util.TestString.Test_String.getDefaultInstance();
          onChanged();
        } else {
          soBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .net.pocrd.test.core.util.Test_String so = 1;</code>
       */
      public net.pocrd.test.core.util.TestString.Test_String.Builder getSoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .net.pocrd.test.core.util.Test_String so = 1;</code>
       */
      public net.pocrd.test.core.util.TestString.Test_StringOrBuilder getSoOrBuilder() {
        if (soBuilder_ != null) {
          return soBuilder_.getMessageOrBuilder();
        } else {
          return so_;
        }
      }
      /**
       * <code>optional .net.pocrd.test.core.util.Test_String so = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          net.pocrd.test.core.util.TestString.Test_String, net.pocrd.test.core.util.TestString.Test_String.Builder, net.pocrd.test.core.util.TestString.Test_StringOrBuilder> 
          getSoFieldBuilder() {
        if (soBuilder_ == null) {
          soBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              net.pocrd.test.core.util.TestString.Test_String, net.pocrd.test.core.util.TestString.Test_String.Builder, net.pocrd.test.core.util.TestString.Test_StringOrBuilder>(
                  so_,
                  getParentForChildren(),
                  isClean());
          so_ = null;
        }
        return soBuilder_;
      }

      // optional int32 i = 3;
      private int i_ ;
      /**
       * <code>optional int32 i = 3;</code>
       *
       * <pre>
       *    repeated Test_String sos = 2;
       * </pre>
       */
      public boolean hasI() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 i = 3;</code>
       *
       * <pre>
       *    repeated Test_String sos = 2;
       * </pre>
       */
      public int getI() {
        return i_;
      }
      /**
       * <code>optional int32 i = 3;</code>
       *
       * <pre>
       *    repeated Test_String sos = 2;
       * </pre>
       */
      public Builder setI(int value) {
        bitField0_ |= 0x00000002;
        i_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 i = 3;</code>
       *
       * <pre>
       *    repeated Test_String sos = 2;
       * </pre>
       */
      public Builder clearI() {
        bitField0_ = (bitField0_ & ~0x00000002);
        i_ = 0;
        onChanged();
        return this;
      }

      // optional string s = 13;
      private java.lang.Object s_ = "";
      /**
       * <code>optional string s = 13;</code>
       *
       * <pre>
       *    repeated int32 is = 4;
       *
       *    optional int64 l = 5;
       *    repeated int64 ls = 6;
       *
       *    optional bool b = 7;
       *    repeated bool bs = 8;
       *
       *    optional float f = 9;
       *    repeated float fs = 10;
       *
       *    optional double d = 11;
       *    repeated double ds = 12;
       * </pre>
       */
      public boolean hasS() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string s = 13;</code>
       *
       * <pre>
       *    repeated int32 is = 4;
       *
       *    optional int64 l = 5;
       *    repeated int64 ls = 6;
       *
       *    optional bool b = 7;
       *    repeated bool bs = 8;
       *
       *    optional float f = 9;
       *    repeated float fs = 10;
       *
       *    optional double d = 11;
       *    repeated double ds = 12;
       * </pre>
       */
      public java.lang.String getS() {
        java.lang.Object ref = s_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          s_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string s = 13;</code>
       *
       * <pre>
       *    repeated int32 is = 4;
       *
       *    optional int64 l = 5;
       *    repeated int64 ls = 6;
       *
       *    optional bool b = 7;
       *    repeated bool bs = 8;
       *
       *    optional float f = 9;
       *    repeated float fs = 10;
       *
       *    optional double d = 11;
       *    repeated double ds = 12;
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSBytes() {
        java.lang.Object ref = s_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          s_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string s = 13;</code>
       *
       * <pre>
       *    repeated int32 is = 4;
       *
       *    optional int64 l = 5;
       *    repeated int64 ls = 6;
       *
       *    optional bool b = 7;
       *    repeated bool bs = 8;
       *
       *    optional float f = 9;
       *    repeated float fs = 10;
       *
       *    optional double d = 11;
       *    repeated double ds = 12;
       * </pre>
       */
      public Builder setS(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        s_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string s = 13;</code>
       *
       * <pre>
       *    repeated int32 is = 4;
       *
       *    optional int64 l = 5;
       *    repeated int64 ls = 6;
       *
       *    optional bool b = 7;
       *    repeated bool bs = 8;
       *
       *    optional float f = 9;
       *    repeated float fs = 10;
       *
       *    optional double d = 11;
       *    repeated double ds = 12;
       * </pre>
       */
      public Builder clearS() {
        bitField0_ = (bitField0_ & ~0x00000004);
        s_ = getDefaultInstance().getS();
        onChanged();
        return this;
      }
      /**
       * <code>optional string s = 13;</code>
       *
       * <pre>
       *    repeated int32 is = 4;
       *
       *    optional int64 l = 5;
       *    repeated int64 ls = 6;
       *
       *    optional bool b = 7;
       *    repeated bool bs = 8;
       *
       *    optional float f = 9;
       *    repeated float fs = 10;
       *
       *    optional double d = 11;
       *    repeated double ds = 12;
       * </pre>
       */
      public Builder setSBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        s_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:net.pocrd.test.core.util.Test_Obj)
    }

    static {
      defaultInstance = new Test_Obj(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:net.pocrd.test.core.util.Test_Obj)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_pocrd_test_core_util_Test_Obj_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_pocrd_test_core_util_Test_Obj_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'net/pocrd/test/core/util/Test_Obj.prot" +
      "o\022\030net.pocrd.test.core.util\032*net/pocrd/t" +
      "est/core/util/Test_String.proto\"S\n\010Test_" +
      "Obj\0221\n\002so\030\001 \001(\0132%.net.pocrd.test.core.ut" +
      "il.Test_String\022\t\n\001i\030\003 \001(\005\022\t\n\001s\030\r \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_pocrd_test_core_util_Test_Obj_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_pocrd_test_core_util_Test_Obj_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_pocrd_test_core_util_Test_Obj_descriptor,
              new java.lang.String[] { "So", "I", "S", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.pocrd.test.core.util.TestString.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
